version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped

    env_file:
      - .env  

    depends_on:
      - db

    environment:

      - DATABASE_URL=postgres://postgres:1@db:5432/usdc_service
    networks:
      - app-network

  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: usdc_service
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: